// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  licensesSidebar: [
    {
      type: 'category',
      label: 'Public Licenses',
      items: [
        {type: 'doc', id: 'index'},
        {type: 'autogenerated', dirName: 'public-licenses'},
      ],
    },
    {
      type: 'category',
      label: 'OpenSource.ngo Licenses',
      items: [{type: 'autogenerated', dirName: 'opensource-ngo-licenses'}],
    },
    {
      type: 'category',
      label: 'Policies',
      items: [{type: 'autogenerated', dirName: 'policies'}],
    },
  ],
};

export default sidebars;
